sudo: required
language: python

python:
  - '3.6'

before_install:
  - "$TRAVIS_BUILD_DIR/scripts/setup.sh"

install:
  - pushd $TRAVIS_BUILD_DIR/bin
  - ./create_cluster.sh
  - popd

script:
  - $TRAVIS_BUILD_DIR/scripts/tests.sh



# deploy:
# - provider: script
#   skip_cleanup: true
#   script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh dev pangeo-dev.informaticslab.co.uk
#     pangeo-dev
#   on:
#     branch: master
# - provider: script
#   skip_cleanup: true
#   script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh hackathon pangeo-hackathon.informaticslab.co.uk
#     pangeo-hackathon
#   on:
#     branch: master
# - provider: script
#   skip_cleanup: true
#   script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh prod jupyterhub.informaticslab.co.uk
#     jupyter
#   on:
#     tags: true
