version: 2
jobs:

  build:
    # working_directory: ~/github
    docker:
      - image: ubuntu:14.04

    steps:
      - checkout

      - run:
          name: setup
          command: ./scripts/setup.sh

      - run:
          name: build
          command: |
            cd bin
            ./create_cluster.sh
            cd ..

      - run:
          name: test
          command: ./scripts/tests.sh



# deploy:
# - provider: script
#   skip_cleanup: true
#   script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh dev pangeo-dev.informaticslab.co.uk
#     pangeo-dev
#   on:
#     branch: master
# - provider: script
#   skip_cleanup: true
#   script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh hackathon pangeo-hackathon.informaticslab.co.uk
#     pangeo-hackathon
#   on:
#     branch: master
# - provider: script
#   skip_cleanup: true
#   script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh prod jupyterhub.informaticslab.co.uk
#     jupyter
#   on:
#     tags: true
