apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: telegraf
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          image: telegraf:1.2.1-alpine
          name: telegraf
          env:
            - name: INFLUX_DB_INGEST_USER
              valueFrom:
                secretKeyRef:
                  name: influx-db-ingest
                  key: username
            - name: INFLUX_DB_INGEST_PASS
              valueFrom:
                secretKeyRef:
                  name: influx-db-ingest
                  key: password
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
              readOnly: true
            - name: dev
              mountPath: /dev
            - name: run
              mountPath: /var/run/docker.sock
            - name: sys
              mountPath: /sys
            - name: log
              mountPath: /var/log
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: dev
          hostPath:
              path: /dev
        - name: run
          hostPath:
              path: /var/run/docker.sock
        - name: sys
          hostPath:
              path: /sys
        - name: log
          hostPath:
              path: /var/log
